### ISSUE TITLE
Setup Deployment Pipeline to preview the project online.

### ISSUE THREAD

**Issue by Buranch** [nandtotetris/computer-visualizer#10]
Lets set up an automatic deployment pipeline that gets triggered whenever a new branch/PR gets created.
Basically what this pipeline does is it will show us a preview of a specific commit. 
Not only this smoothes up our development but it also boosts our communication while tackling bugs and discussing features. 

We can choose between Netlify(https://www.netlify.com/) and TravisCI(https://travis-ci.com/). I'm not sure if they are totally free. Feel free if you have other tool recommendations.

**Comment by henites72** [comment]
@Buranch @mezzzi I think we can close this issue now.

**Comment by mezzzi** [comment]
Wait, @henites72 can you post here a little description of how it was done. For reference.

**Comment by Buranch** [comment]
@henites72 also if you can add as an admin on the Netlify dashboard we would appreciate it.

**Comment by henites72** [comment]
> Wait, @henites72 can you post here a little description of how it was done. For reference.

https://app.netlify.com/sites/computer-visualizer/settings/deploys
I just active an option to deploy any pull requests on the deploy panel.

**Comment by henites72** [comment]
<img width="1273" alt="Screen Shot 2020-02-29 at 12 12 01 PM" src="https://user-images.githubusercontent.com/61501567/75604720-c27d6180-5aec-11ea-8cd1-60b087d11ea0.png">

Let me check if there is an option to add admins.

**Comment by henites72** [comment]
@Buranch @mezzzi Is there anything left for this issue to be closed?

**Comment by Buranch** [comment]
@henites72 , good job.
