### ISSUE TITLE
Setup a UI/UX project management tool.

### ISSUE THREAD

**Issue by Buranch** [nandtotetris/computer-visualizer#11]
As per slack discussion, lets set up a UI/UX tool that we may brainstorm the UI/UX for the app.

**Comment by Buranch** [comment]
After researching a few options, for now, I've decided to go with Figma. Their free plan allows one project, so we're good. And I find it more intuitive for collaboration. 

https://www.figma.com/file/0OakhR65Q57oQn9oFmls3d/Untitled

**Comment by henites72** [comment]
I have used `Figma` before and it is cool.

**Comment by Buranch** [comment]
Ok, since we all are in, let's consider this issue closed.
