### ISSUE TITLE
Decide between `javascript` and `typescript`

### ISSUE THREAD

**Issue by mezzzi** [nandtotetris/computer-visualizer#2]
Though this project will be done with react, there is still a choice when it comes to choosing a programming language. We can go either with `javascript` or `typescript`. Each might have its own advantage and disadvantage. Before rushing into picking one of them at random, we need to do a little research and have also a discussion as to why one of them will help execute the project much faster, better, and smoother. This issue should resolve any concerns related to the choice of programming language.

**Comment by mezzzi** [comment]
I personally think `javascript` to be the better choice. Because right now our priority is not code maintainability or readability, or intellisence for that matter. We just want to quickly implement certain features. And I believe for quick implementation the flexibility of javascript will come in very handy. I believe also the setup process will be much easier with javascript.

Let's quickly decide this and get on to setting up the project.

@henites72 let us know your thoughts on this.

**Comment by Buranch** [comment]
@mezzzi I prefer js as well. I fear `typescript` may slow us down with unnecessary tasks like preparing a model for each API response or any variable for that matter.

And since we're using React, we can alternatively use [PropTypes](https://reactjs.org/docs/typechecking-with-proptypes.html) which to some degree offers typescript feature of type agreement among developers.

**Comment by Buranch** [comment]
My initial thought was `typescript` because the existing code is built on `typescript`. 
I'm not sure if that gets affected?

**Comment by mezzzi** [comment]
@Buranch I think we can easily convert the existing typescript code to javascript. It shouldn't be a problem.

So, I am considering this issue resolved now.
