### ISSUE TITLE
Access the feasibility of converting typescript classes into JS classes?

### ISSUE THREAD

**Issue by henites72** [nandtotetris/computer-visualizer#3]
In issue #2, we decided to use `Javascript` as a programming language for our system. But we implement all the abstractions in the system using `Typescript`, so we want to show a converted abstraction, completely written in Javascript?

**Comment by mezzzi** [comment]
@henites72 can you post here an example typescript class, a small one if possible?

**Comment by henites72** [comment]
@mezzzi should it be from the abstractions or some sample `OOP` code in `Typescript`?

**Comment by mezzzi** [comment]
I have found this class from @henites72's repository (book-projects). We can show the feasibility using this as a sample typescript class.
```
class SymbolTable {
  public table: Object;

  constructor() {
    this.intilalizeSymbolTable();
  }

  intilalizeSymbolTable() {
    this.table = {
      SP: 0,
      LCL: 1,
      ARG: 2,
      THIS: 3,
      THAT: 4,
      R0: 0,
      R1: 1,
      SCREEN: 16384,
      KBD: 24576
    };
  }

  addEntry(symbol: string, address: number) {
    this.table[symbol] = address;
  }

  contains(symbol: string): boolean {
    return this.table.hasOwnProperty(symbol);
  }

  getAddress(symbol: string): number {
    if (this.contains(symbol)) return this.table[symbol];
  }
}

export default SymbolTable;
```

**Comment by henites72** [comment]
Great @mezzzi!

**Comment by Buranch** [comment]
I'm experimenting with this tool https://www.typescriptlang.org/play/
looks promising so far.

**Comment by mikereze** [comment]
So are we going to write the whole code in Javascript and then we are going to find a tool to convert it to Typescript? is that what you meant?

**Comment by mezzzi** [comment]
No @mikereze, it is the other way around.

**Comment by mezzzi** [comment]
The sample `typescript` code posted above can be converted into the following `javascript` equivalent:
```
class SymbolTable {
    constructor() {
        this.intilalizeSymbolTable();
    }
    intilalizeSymbolTable() {
        this.table = {
            SP: 0,
            LCL: 1,
            ARG: 2,
            THIS: 3,
            THAT: 4,
            R0: 0,
            R1: 1,
            R2: 2,
            R3: 3,
            R4: 4,
            R5: 5,
            R6: 6,
            R7: 7,
            R8: 8,
            R9: 9,
            R10: 10,
            R11: 11,
            R12: 12,
            R13: 13,
            R14: 14,
            R15: 15,
            SCREEN: 16384,
            KBD: 24576
        };
    }
    addEntry(symbol, address) {
        this.table[symbol] = address;
    }
    contains(symbol) {
        return this.table.hasOwnProperty(symbol);
    }
    getAddress(symbol) {
        if (this.contains(symbol))
            return this.table[symbol];
    }
}
export default SymbolTable;
```
There is this tool that can help with the conversion: https://www.typescriptlang.org/play/index.html. Thanks @Buranch for suggesting it. But we shouldn't rely entirely on the tool. We need to double check each converted code to make sure there isn't error in the conversion.

**Comment by Buranch** [comment]
@mezzi yes  I've already suggested a human review back in our slack
discussion

**Comment by mezzzi** [comment]
This article (https://medium.com/javascript-scene/the-typescript-tax-132ff4cb175b) provides a detailed comparison, pro and con analysis, between `js` and `typescript`. And the author updates the scores to reflect latest developments in each ecosystem. As of now, the scores favors `js` . So that kind of puts us in the right track, at least thinking of long term benefits to be gained, as the project matures and scales.
