### ISSUE TITLE
Set up the project using `create-react-app`

### ISSUE THREAD

**Issue by henites72** [nandtotetris/computer-visualizer#5]
We want to setup the project with `create-react-app`.

**Comment by mezzzi** [comment]
@henites72 let's just do it only with `create-react-app` for now.

**Comment by henites72** [comment]
Let's talk the packages we need here?

**Comment by mezzzi** [comment]
We can add the packages when we need them, wouldn't that be better?

**Comment by Buranch** [comment]
@henites72 instead of predicting all packages we need right now, let just setup the CRA and we add packages as needed.

For instance, the next issue can be setting up React router, at that PR we obvious need `react-router`

**Comment by henites72** [comment]
Great guys, that would be better even for management.

**Comment by mezzzi** [comment]
@henites72 update the description to make this issue only about setting up the project using `create-react-app`.

**Comment by henites72** [comment]
@mezzzi updated both the PR title and the description.
